---
argument_specs:
  main:
    options:
      k8s_name:
        type: str
      k8s_namespace:
        type: str
        required: true
      image:
        type: str
        required: true
      tag_prefix:
        type: str
        required: true
      app_port:
        type: str
      app_env:
        type: dict
      app_host:
        type: str
        required: true
      base_path:
        type: str
      auth_middelware_name:
        type: str
        required: true
      auth_middelware_namespace:
        type: str
        required: true
      spring_actuator_port:
        type: str
      spring_admin_server_name:
        type: str
        required: true
      spring_admin_server_namespace:
        type: str
        required: true
      spring_admin_server_port:
        type: int
        required: true
