apiVersion: v1
kind: Service
metadata:
  name: {{ k8s_name }}
  namespace: {{ k8s_namespace }}
  labels:
    app: {{ k8s_name }}
spec:
  ports:
    - port: {{ app_port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ nginx_metrics_port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app: {{ k8s_name }}